
import { createContext, useState, useContext, ReactNode } from "react";

type LanguageContextType = {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
};

// Create translations for both languages
const translations = {
  sv: {
    // Navigation
    "nav.home": "Hem",
    "nav.services": "Tjänster",
    
    "nav.admin": "Admin",
    "nav.pricing": "Priser & Bokning",
    "nav.contact": "Kontakta oss",
    
    // Hero section
    "hero.subtitle": "Professionell Trädvård i Sverige",
    "hero.title1": "Expert Trädkirurgi",
    "hero.title2": "& Trädvård",
    "hero.description": "Hardimans Trädvård är ett professionellt arboristföretag som utför vård och underhåll av träd samt trädfällning över hela Sverige. Certifierade arborister med över 20 års erfarenhet.",
    "hero.cta1": "Kontakta Oss",
    "hero.cta2": "Våra Tjänster",
    
    // About/Services section
    "about.badge": "Våra Tjänster",
    "about.title": "Professionell Trädvård för Alla Behov",
    "about.description": "Vår filosofi och vårt mål är att utföra tjänster av högsta kvalitet inom all trädvård och vi erbjuder ärliga och kloka råd för de projekt som vi åtar oss. Vi strävar efter att uppmärksamma trädens viktiga roll i vår miljö och att våra kunder får rätt slags vård för sina träd.",
    
    // Service items
    "service.pruning": "Trädbeskärning",
    "service.pruning.desc": "Professionell beskärning för att förbättra trädens hälsa, säkerhet och utseende.",
    "service.felling": "Trädfällning",
    "service.felling.desc": "Säker och kontrollerad fällning av träd i alla miljöer, även på begränsade ytor.",
    "service.shaping": "Trädformning",
    "service.shaping.desc": "Specialiserad beskärning för att forma träd enligt specifika estetiska önskemål.",
    "service.care": "Trädvård",
    "service.care.desc": "Förebyggande vård och behandling av sjukdomar för att säkerställa trädens långsiktiga hälsa.",
    "service.grinding": "Stubbfräsning",
    "service.grinding.desc": "Effektiv borttagning av stubbar för att förbereda marken för ny plantering eller anläggning.",
    "service.consulting": "Rådgivning",
    "service.consulting.desc": "Expertråd och konsultation för trädgårdsplanering och långsiktig trädvård.",
    
    // Stats
    "stats.experience": "Års Erfarenhet",
    "stats.projects": "Projekt Avslutade",
    "stats.clients": "Nöjda Kunder",
    "stats.certified": "Certifierade Arborister",
    
    // Contact section
    "contact.badge": "Kontakta Oss",
    "contact.title": "Vill du veta mer?",
    "contact.description": "Har du ett projekt i åtanke eller vill du veta mer om våra tjänster? Vi ser fram emot att höra från dig.",
    "contact.email": "E-post",
    "contact.phone": "Telefon",
    "contact.social": "Sociala Medier",
    "contact.location": "Serviceområde",
    "contact.hours": "Öppettider",
    "contact.monday": "Måndag - Fredag",
    "contact.saturday": "Lördag",
    "contact.sunday": "Söndag",
    "contact.byagreement": "Efter överenskommelse",
    "contact.closed": "Stängt",
    "contact.booking.title": "Boka tjänst",
    "contact.booking.description": "Fyll i formuläret nedan för att boka en plats och betala deposition.",
    "contact.booking.name": "Namn",
    "contact.booking.namePlaceholder": "Ditt namn",
    "contact.booking.email": "E-post",
    "contact.booking.emailPlaceholder": "Din e-postadress",
    "contact.booking.phone": "Telefon",
    "contact.booking.phonePlaceholder": "Ditt telefonnummer",
    "contact.booking.location": "Plats",
    "contact.booking.locationPlaceholder": "Ange adress eller område",
    "contact.booking.service": "Tjänst",
    "contact.booking.preferredDate": "Önskat datum",
    "contact.booking.deposit": "Deposition",
    "contact.booking.message": "Meddelande",
    "contact.booking.messagePlaceholder": "Ytterligare information eller preferenser",
    "contact.booking.button": "Skicka bokning",
    "contact.booking.payDeposit": "Betala deposition",
    "contact.booking.payDepositOpt": "Betala deposition nu (valfritt)",
    "contact.booking.errorTitle": "Fyll i alla fält",
    "contact.booking.errorFields": "Vänligen ange namn, e-post, telefon, plats och datum.",
    "contact.booking.successTitle": "Bokning skickad",
    "contact.booking.successDescription": "Tack! Vi har sparat din bokning och återkommer snart.",
    "contact.booking.web3formsErrorTitle": "Det gick inte att skicka bokningen",
    "contact.booking.web3formsErrorDescription": "Ett fel uppstod vid försök att skicka bokningen. Försöker öppna din e-postklient som fallback.",
    "contact.booking.emailSubjectPrefix": "Bokningsförfrågan",
    "contact.booking.emailBodyLabel": "Namn",
    "contact.booking.emailBodyEmail": "E-post",
    "contact.booking.emailBodyPhone": "Telefon",
    "contact.booking.emailBodyLocation": "Plats",
    "contact.booking.emailBodyService": "Tjänst",
    "contact.booking.emailBodyDate": "Datum",
    "contact.booking.emailBodyDeposit": "Deposition",
    "contact.booking.emailBodyMessage": "Meddelande",
    "payment.badge": "Betalningsalternativ",
    "payment.title": "Deposition och betalningsmetoder",
    "payment.description": "Välj önskad betalningsmetod för att säkra din bokning med PayPal, Revolut eller banköverföring.",
    "payment.paypal.title": "PayPal",
    "payment.paypal.description": "Skicka din deposition via PayPal för snabb bekräftelse.",
    "payment.paypal.accountLabel": "PayPal-länk",
    "payment.paypal.button": "Betala med PayPal",
    "payment.revolut.title": "Revolut",
    "payment.revolut.description": "Använd Revolut för enkla mobila betalningar.",
    "payment.revolut.accountLabel": "Revolut-nummer",
    "payment.revolut.ownerLabel": "Kontoinnehavare",
    "payment.bank.title": "Banköverföring",
    "payment.bank.description": "Använd banköverföring om du föredrar direkt insättning till vårt konto.",
    "payment.bank.accountName": "Kontonamn",
    "payment.bank.iban": "IBAN",
    "payment.bank.bic": "BIC",
    "payment.noteTitle": "Observera",
    "payment.noteDescription": "Efter att du skickat depositionen, spara din betalningsbekräftelse och kontakta oss om du behöver ytterligare hjälp.",
    "pricing.badge": "Priser",
    "pricing.title": "Priser & Deposition",
    "pricing.description": "Priserna varierar beroende på projekt. När vi bekräftat en offert kan en deposition betalas med någon av alternativen nedan.",
    "pricing.example.small": "Små jobb — startpris",
    "pricing.example.medium": "Medelstora jobb — indikativt pris",
    "pricing.example.large": "Större arbeten — från",
    "pricing.contactForPricing": "Kontakta oss för prisuppgift",
    "pricing.noteBeforePayments": "Observera: slutligt pris bestäms efter offert. Depositionsalternativ finns nedan för att säkra din bokning.",
    "pricing.bookNow": "Boka nu",
    "pricing.conditions.title": "Prissättningsvillkor",
    "pricing.conditions.description": "Alla priser baseras på den slutliga offert som bekräftas efter inspektion. Här är de viktigaste villkoren:",
    "pricing.conditions.item1": "Offerten är indikativ och kan justeras efter platsbesök.",
    "pricing.conditions.item2": "Depositionsbeloppet säkrar tiden och tas av från slutfakturan.",
    "pricing.conditions.item3": "Eventuella ändringar efter offert kan påverka det slutliga priset.",
    "pricing.conditions.item4": "Slutgiltig kostnad faktureras först när arbetet har bekräftats.",

    // Footer
    "footer.rights": "Alla rättigheter förbehållna.",
    "footer.certified": "Certified Arborist",
    "footer.member": "Hardimans Trädvård | Certifierade Arborister",
    
    // Work page
    "work.title": "Våra Projekt",
    "work.subtitle": "Se exempel på vårt arbete och hur vi tar hand om träd i olika miljöer",
    "work.project1.title": "Villa i Göteborg ",
    "work.project1.description": "Beskärning och formning av flera stora ekar för att förbättra ljusinsläpp och säkerhet.",
    "work.project2.title": "Kontorspark i Göteborg",
    "work.project2.description": "Borttagning av stormskadade träd och plantering av nya arter för framtida tillväxt.",
    "work.project3.title": "Stadspark i Malmö",
    "work.project3.description": "Hälsobedömning och vård av historiska träd i centrala Malmö.",
    "work.tags.pruning": "Beskärning",
    "work.tags.removal": "Trädfällning",
    "work.tags.health": "Hälsovård",
    "work.tags.residential": "Bostadsområde",
    "work.tags.commercial": "Kommersiellt",
    "work.tags.parks": "Parkområde",

    // Admin dashboard
    "admin.badge": "Admin Dashboard",
    "admin.title": "Keyword Monitoring",
    "admin.subtitle": "Monitor keyword performance and status for English and Swedish campaigns.",
    "admin.metric.keywords": "Totalt antal sökord",
    "admin.metric.pages": "Sporrade sidor",
    "admin.metric.english": "Engelska sökord",
    "admin.metric.swedish": "Svenska sökord",
    "admin.metric.active": "Aktiva sökord",
    "admin.table.caption": "Liveövervakning av sökord för trädvård och arboristtermer.",
    "admin.column.keyword": "Sökord",
    "admin.column.source": "Källa URL",
    "admin.column.language": "Språk",
    "admin.column.volume": "Sökvolym",
    "admin.column.trend": "Trend",
    "admin.column.status": "Status",
    "admin.source.title": "Sporrade källsidor",
    "admin.source.description": "Lägg till sökord och sid-URL:er du vill övervaka på din egen webbplats.",
    "admin.form.keyword": "Sökordsfras",
    "admin.form.source": "Källa URL",
    "admin.form.volume": "Beräknad volym",
    "admin.form.language": "Språk",
    "admin.form.trend": "Trend",
    "admin.form.status": "Status",
    "admin.form.add": "Lägg till sökord",
    "admin.action.save": "Spara",
    "admin.action.cancel": "Avbryt",
    "admin.action.edit": "Redigera",
    "admin.action.delete": "Ta bort",
    "admin.action.logout": "Logga ut",
    "admin.google.title": "Google Connect",
    "admin.google.description": "Connect to Google to review Search Console sites and monitor keyword health.",
    "admin.login.badge": "Admin-inloggning",
    "admin.login.title": "Logga in på din instrumentpanel",
    "admin.login.subtitle": "Ange administratörslösenordet för att komma åt instrumentpanelen.",
    "admin.login.password": "Lösenord",
    "admin.login.passwordPlaceholder": "Ange ditt lösenord",
    "admin.login.submit": "Logga in",
    "admin.login.errorRequired": "Lösenord krävs.",
    "admin.login.errorInvalid": "Ogiltigt lösenord. Försök igen.",
    "admin.google.status": "Google Status:",
    "admin.google.connect": "Connect with Google",
    "admin.google.connected": "Connected",
    "admin.google.disconnected": "Disconnected",
    "admin.google.pending": "Connecting…",
    "admin.google.error": "Unable to connect to Google.",
    "admin.google.missingClientId": "Google client ID is not configured.",
    "admin.google.invalidClientId": "Google client ID must be a valid OAuth client identifier ending with .apps.googleusercontent.com.",
    "admin.google.user": "Signed in as",
    "admin.google.sites.title": "Search Console Sites",
    "admin.google.noSites": "No Search Console sites found or authorized yet.",
    "admin.track.ownDescription": "Track your own target keywords and performance metrics in one place.",
    "admin.bookings.title": "Bookings",
    "admin.bookings.description": "View and manage booking requests saved in the browser.",
    "admin.bookings.refresh": "Refresh bookings",
    "admin.bookings.clear": "Clear all",
    "admin.bookings.table.caption": "Latest booking requests.",
    "admin.bookings.column.id": "ID",
    "admin.bookings.column.name": "Name",
    "admin.bookings.column.email": "Email",
    "admin.bookings.column.phone": "Phone",
    "admin.bookings.column.message": "Meddelande",
    "admin.bookings.column.date": "Date",
    "admin.bookings.column.deposit": "Deposit",
    "admin.bookings.column.message": "Message",
    "admin.bookings.column.notes": "Notes",
    "admin.bookings.notePlaceholder": "Write notes...",
    "admin.bookings.column.actions": "Actions",
  },
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.services": "Services",
    
    "nav.admin": "Admin",
    "nav.contact": "Contact Us",
    "nav.pricing": "Pricing & Booking",
    
    // Hero section
    "hero.subtitle": "Professional Tree Care in Sweden",
    "hero.title1": "Expert Tree Surgery",
    "hero.title2": "& Tree Care",
    "hero.description": "Hardimans Tree Care is a professional arborist company that performs tree care, maintenance, and tree removal throughout Sweden. Certified arborists with over 20 years of experience.",
    "hero.cta1": "Contact Us",
    "hero.cta2": "Our Services",
    
    // About/Services section
    "about.badge": "Our Services",
    "about.title": "Professional Tree Care for All Needs",
    "about.description": "Our philosophy and goal is to perform services of the highest quality in all tree care, and we offer honest and wise advice for the projects we undertake. We strive to highlight the important role of trees in our environment and ensure our customers receive the right kind of care for their trees.",
    
    // Service items
    "service.pruning": "Tree Pruning",
    "service.pruning.desc": "Professional pruning to improve tree health, safety, and appearance.",
    "service.felling": "Tree Removal",
    "service.felling.desc": "Safe and controlled tree felling in all environments, even in confined spaces.",
    "service.shaping": "Tree Shaping",
    "service.shaping.desc": "Specialized pruning to shape trees according to specific aesthetic preferences.",
    "service.care": "Tree Care",
    "service.care.desc": "Preventive care and treatment of diseases to ensure long-term tree health.",
    "service.grinding": "Stump Grinding",
    "service.grinding.desc": "Efficient removal of stumps to prepare the ground for new planting or development.",
    "service.consulting": "Consulting",
    "service.consulting.desc": "Expert advice and consultation for garden planning and long-term tree care.",
    
    // Stats
    "stats.experience": "Years of Experience",
    "stats.projects": "Completed Projects",
    "stats.clients": "Happy Clients",
    "stats.certified": "Certified Arborists",
    
    // Contact section
    "contact.badge": "Contact Us",
    "contact.title": "Want to Know More?",
    "contact.description": "Do you have a project in mind or want to know more about our services? We look forward to hearing from you.",
    "contact.email": "Email",
    "contact.phone": "Phone",
    "contact.social": "Social Media",
    "contact.location": "Service Area",
    "contact.hours": "Opening Hours",
    "contact.monday": "Monday - Friday",
    "contact.saturday": "Saturday",
    "contact.sunday": "Sunday",
    "contact.byagreement": "By appointment",
    "contact.closed": "Closed",
    "contact.booking.title": "Book a Service",
    "contact.booking.description": "Fill out the form below to book an appointment",
    "contact.booking.name": "Name",
    "contact.booking.namePlaceholder": "Your name",
    "contact.booking.email": "Email",
    "contact.booking.emailPlaceholder": "Your email address",
    "contact.booking.phone": "Phone",
    "contact.booking.phonePlaceholder": "Your phone number",
    "contact.booking.location": "Location",
    "contact.booking.locationPlaceholder": "Enter address or area",
    "contact.booking.service": "Service",
    "contact.booking.preferredDate": "Preferred date",
    "contact.booking.deposit": "Deposit",
    "contact.booking.message": "Message",
    "contact.booking.messagePlaceholder": "Additional information or preferences",
    "contact.booking.button": "Submit booking",
    "contact.booking.payDeposit": "Pay deposit",
    "contact.booking.payDepositOpt": "Pay deposit now (optional)",
    "contact.booking.errorTitle": "Complete all fields",
    "contact.booking.errorFields": "Please enter name, email, phone, location and date.",
    "contact.booking.successTitle": "Booking submitted",
    "contact.booking.successDescription": "Thank you! Your booking has been saved and we will contact you soon.",
    "contact.booking.web3formsErrorTitle": "Unable to send booking",
    "contact.booking.web3formsErrorDescription": "An error occurred while submitting the booking. Falling back to your email client.",
    "contact.booking.emailSubjectPrefix": "Booking request",
    "contact.booking.emailBodyLabel": "Name",
    "contact.booking.emailBodyEmail": "Email",
    "contact.booking.emailBodyPhone": "Phone",
    "contact.booking.emailBodyLocation": "Location",
    "contact.booking.emailBodyService": "Service",
    "contact.booking.emailBodyDate": "Date",
    "contact.booking.emailBodyDeposit": "Deposit",
    "contact.booking.emailBodyMessage": "Message",
    "payment.badge": "Payment Options",
    "payment.title": "Deposit and Payment Methods",
    "payment.description": "Choose the payment method you prefer to secure your booking with PayPal, Revolut, or bank transfer.",
    "payment.paypal.title": "PayPal",
    "payment.paypal.description": "Send your deposit through PayPal for fast confirmation.",
    "payment.paypal.accountLabel": "PayPal link",
    "payment.paypal.button": "Pay with PayPal",
    "payment.revolut.title": "Revolut",
    "payment.revolut.description": "Use Revolut for easy mobile payments.",
    "payment.revolut.accountLabel": "Revolut number",
    "payment.revolut.ownerLabel": "Account name",
    "payment.bank.title": "Bank Transfer",
    "payment.bank.description": "Use bank transfer if you prefer a direct deposit to our account.",
    "payment.bank.accountName": "Account name",
    "payment.bank.iban": "IBAN",
    "payment.bank.bic": "BIC",
    "payment.noteTitle": "Please note",
    "payment.noteDescription": "After sending the deposit, please keep your payment confirmation and contact us if you need any further assistance.",
    "pricing.badge": "Pricing",
    "pricing.title": "Prices & Deposit Options",
    "pricing.description": "Pricing varies for each project. Once we confirm a quote you can pay a deposit using any of the options below.",
    "pricing.example.small": "Small jobs — starting from",
    "pricing.example.medium": "Medium jobs — indicative",
    "pricing.example.large": "Larger jobs — from",
    "pricing.contactForPricing": "Contact us for pricing",
    "pricing.noteBeforePayments": "Note: final price depends on the confirmed quote. Deposits can be paid using any of the methods below to secure your booking.",
    "pricing.bookNow": "Book now",
    "pricing.conditions.title": "Pricing conditions",
    "pricing.conditions.description": "All examples are indicative. Final pricing depends on the confirmed quote and the following conditions:",
    "pricing.conditions.item1": "Quoted prices may be adjusted after an on-site assessment.",
    "pricing.conditions.item2": "The deposit secures the booking and is deducted from the final invoice.",
    "pricing.conditions.item3": "Changes after quote may affect the final price.",
    "pricing.conditions.item4": "The final cost is settled only after work confirmation.",

    // Footer
    "footer.rights": "All rights reserved.",
    "footer.certified": "Certified Arborists",
    "footer.member": "Hardimans Tree Care | Certified Arborists",
    
    // Work page
    "work.title": "Our Projects",
    "work.subtitle": "See examples of our work and how we care for trees in various environments",
    "work.project1.title": "Residence in Göteborg",
    "work.project1.description": "Pruning and shaping of several large oak trees to improve light penetration and safety.",
    "work.project2.title": "Office Park in Gothenburg",
    "work.project2.description": "Removal of storm-damaged trees and planting of new species for future growth.",
    "work.project3.title": "City Park in Malmö",
    "work.project3.description": "Health assessment and care of historic trees in central Malmö.",
    "work.tags.pruning": "Pruning",
    "work.tags.removal": "Tree Removal",
    "work.tags.health": "Health Care",
    "work.tags.residential": "Residential",
    "work.tags.commercial": "Commercial",
    "work.tags.parks": "Park Area",

    // Admin dashboard
    "admin.badge": "Admin Dashboard",
    "admin.title": "Keyword Monitoring",
    "admin.subtitle": "Monitor keyword performance and status for English and Swedish campaigns.",
    "admin.metric.keywords": "Total Keywords",
    "admin.metric.pages": "Tracked Pages",
    "admin.metric.english": "English Keywords",
    "admin.metric.swedish": "Swedish Keywords",
    "admin.metric.active": "Active Keywords",
    "admin.table.caption": "Live keyword monitoring for tree care and arborist search terms.",
    "admin.column.keyword": "Keyword",
    "admin.column.source": "Source URL",
    "admin.column.language": "Language",
    "admin.column.volume": "Search Volume",
    "admin.column.trend": "Trend",
    "admin.column.status": "Status",
    "admin.source.title": "Tracked Source Pages",
    "admin.source.description": "Add keywords and the page URLs you want to monitor for your own site.",
    "admin.form.keyword": "Keyword phrase",
    "admin.form.source": "Source URL",
    "admin.form.volume": "Estimated volume",
    "admin.form.language": "Language",
    "admin.form.trend": "Trend",
    "admin.form.status": "Status",
    "admin.form.add": "Add keyword",
    "admin.action.save": "Save",
    "admin.action.cancel": "Cancel",
    "admin.action.edit": "Edit",
    "admin.action.delete": "Delete",
    "admin.visitor.title": "Visitor sessions",
    "admin.visitor.description": "See where visitors came from, how long they stayed, and where they left.",
    "admin.visitor.refresh": "Refresh sessions",
    "admin.visitor.table.caption": "Recent visitor sessions.",
    "admin.bookings.title": "Bookings",
    "admin.bookings.description": "View and manage booking requests saved in the browser.",
    "admin.bookings.refresh": "Refresh bookings",
    "admin.bookings.clear": "Clear all",
    "admin.bookings.table.caption": "Latest booking requests.",
    "admin.bookings.column.id": "ID",
    "admin.bookings.column.name": "Name",
    "admin.bookings.column.email": "Email",
    "admin.bookings.column.phone": "Phone",
    "admin.bookings.column.date": "Date",
    "admin.bookings.column.deposit": "Deposit",
    "admin.bookings.column.notes": "Notes",
    "admin.bookings.notePlaceholder": "Write notes...",
    "admin.bookings.column.actions": "Actions",
    "admin.visitor.column.sessionId": "Session",
    "admin.visitor.column.referrer": "Referrer",
    "admin.visitor.column.pages": "Pages visited",
    "admin.visitor.column.duration": "Duration",
    "admin.visitor.column.ipLocation": "IP Location",
    "admin.metric.sessions": "Sessions",
    "admin.metric.averageDuration": "Average duration",
    "admin.metric.topReferrer": "Top referrer",
    "admin.metric.topExitPage": "Top exit page",
    "admin.google.title": "Google Connect",
    "admin.google.description": "Connect to Google to review Search Console sites and monitor keyword health.",
    "admin.google.status": "Google Status:",
    "admin.google.connect": "Connect with Google",
    "admin.google.connected": "Connected",
    "admin.google.disconnected": "Disconnected",
    "admin.google.pending": "Connecting…",
    "admin.google.error": "Unable to connect to Google.",
    "admin.google.missingClientId": "Google client ID is not configured.",
    "admin.google.invalidClientId": "Google client ID must be a valid OAuth client identifier ending with .apps.googleusercontent.com.",
    "admin.google.user": "Signed in as",
    "admin.google.sites.title": "Search Console Sites",
    "admin.google.noSites": "No Search Console sites found or authorized yet.",
    "admin.track.ownDescription": "Track your own target keywords and performance metrics in one place.",
    "admin.login.badge": "Admin Login",
    "admin.login.title": "Sign in to your dashboard",
    "admin.login.subtitle": "Enter the admin password to access the dashboard.",
    "admin.login.password": "Password",
    "admin.login.passwordPlaceholder": "Enter your password",
    "admin.login.submit": "Sign in",
    "admin.login.errorRequired": "Password is required.",
    "admin.login.errorInvalid": "Invalid password. Please try again.",
    "admin.action.logout": "Log out",
  }
};

// Create the context with default values
export const LanguageContext = createContext<LanguageContextType>({
  language: "sv",
  setLanguage: () => {},
  t: (key: string) => key,
});

// Create a provider component
export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState("sv");

  // Translation function
  const t = (key: string): string => {
    if (key.startsWith('admin.')) {
      // Always render admin UI in English, even if the site language is Swedish.
      // @ts-ignore - We know these keys exist in English.
      return translations.en[key] || translations[language][key] || key;
    }

    // @ts-ignore - We know these keys exist
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Custom hook to use the language context
export const useLanguage = () => useContext(LanguageContext);
